# Generated by Django 4.0.3 on 2022-05-03 10:24

import WebIStudy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=WebIStudy.models.filepath)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Forum_name', models.CharField(max_length=300)),
                ('Description', models.CharField(max_length=300)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=WebIStudy.models.filepath)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Forum_name', models.CharField(max_length=300)),
                ('Author', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('study_year', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=WebIStudy.models.filepath)),
                ('blocked', models.CharField(max_length=50, null=True)),
                ('manager', models.CharField(max_length=50, null=True)),
                ('forum_manage', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
