# Generated by Django 4.0.3 on 2022-04-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebIStudy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Forum_name', models.CharField(max_length=300)),
                ('Description', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
