# Generated by Django 4.0.3 on 2022-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebIStudy', '0002_blocklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='forummessage',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
