# Generated by Django 4.0.3 on 2022-04-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebIStudy', '0003_alter_forum_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='picture',
            field=models.ImageField(upload_to='Pictures/'),
        ),
    ]
