# Generated by Django 4.0.3 on 2022-04-26 16:00

import WebIStudy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebIStudy', '0012_alter_forum_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='forum_manage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=WebIStudy.models.filepath),
        ),
    ]
