# Generated by Django 4.0.3 on 2022-04-26 16:24

import WebIStudy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebIStudy', '0013_user_blocked_user_forum_manage_user_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=WebIStudy.models.filepath),
        ),
    ]
