# Generated by Django 4.0.3 on 2022-04-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebIStudy', '0014_admin_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
