# Generated by Django 4.0.3 on 2022-04-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebIStudy', '0016_forummessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
